sonar.projectKey=TyranocarlosRex_Sistema-Dual
sonar.organization=tyranocarlosrex

sonar.sources=app,bootstrap,config,database,resources/js,resources/views,routes
sonar.tests=tests

sonar.exclusions=coverage/**,docs/**,resources/views/scribe/**,public/build/**,node_modules/**,vendor/**,storage/**,bootstrap/cache/**
sonar.coverage.exclusions=database/**,routes/**,config/**,resources/views/**
sonar.test.inclusions=tests/**
